server:
  port: 8081


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.196.161.74/mysql
    username: root
    password: root
    # 使用hikari数据源
    type: com.zaxxer.hikari.HikariDataSource
    minimum-idle: 5
    maximum-pool-size: 15
    auto-commit: true
    idle-timeout: 30000
    pool-name: PCMakerHikariCP
    max-lifetime: 1800000
    connection-timeout: 30000
    connection-test-query: SELECT 1


mybatis-plus:
  mapper-locations: classpath:com/xujin/study/mapper/mapping/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.xujin.study.model
  global-config:
    db-config:
      column-underline: true


---
spring:
  redis:
    database: 1
    host: 121.196.161.74
    port: 6379  #端口
    password: xujin123456

